          - name: Build WGold 2.1 package
            run: |
          mkdir -p wgold/DEBIAN
          mkdir -p wgold/Library/MobileSubstrate/DynamicLibraries
          mkdir -p wgold/Library/Application Support

          unzip -q WGold.bundle.zip
          rm WGold.bundle.zip

          mv WGold.dylib wgold/Library/MobileSubstrate/DynamicLibraries/
          mv WGold.bundle wgold/Library/Application Support/
          mv WGold.plist wgold/Library/MobileSubstrate/DynamicLibraries/

          
       
          # Creazione del file control di DEBIAN
          - name: Create control file
            run: |
          cat > wgold/DEBIAN/control <<EOF
          Package: com.wgold
          Name: WGold
          Depends: mobilesubstrate
          Version: 2.1
          Architecture: iphoneos-arm
          Description: WGold
          Maintainer: joe
          Author: joe
          Section: Tweaks
          SileoDepiction: https://apt.fouadraheb.com/package/com.fouadraheb.watusi3

          dpkg-deb --build wgold wgold.deb
          
          test -f wgold/Library/MobileSubstrate/DynamicLibraries/YTLite.dylib
          test -f wgold/Library/MobileSubstrate/DynamicLibraries/YTLite.plist
          test -d "wgold/Library/Application Support/YTLite.bundle"
